### ISSUE TITLE
After import users are duplicated during traits save

### ISSUE THREAD

**Issue by michaloo** [hull-ships/hull-hubspot#10]
@sbellity - you have already said about that problem, but in case of Mailchimp integration we do it the other way around. Right now, when I have an imported user which will be sent to Hubspot, modified then and updated using following code:
`this.hullClient.as({ email }).traits(traits);`
it will create a duplicate for that email. Next updates works updating the second Hull user.

Previously you had an idea how to solve it.

**Comment by unity** [comment]
@sbellity this is related to hull's email resolution right ? - if so can we add this to the related Trello card ?

**Comment by sbellity** [comment]
@unity @michaloo yep. The change we introduced yesterday should resolve this issue

**Comment by michaloo** [comment]
I will test it today and let you know.

**Comment by michaloo** [comment]
Sorry about the delay, got into the mailchimp ship. I've just tested this scenario on beta. There were no duplicates created. Issue resolved.
