### ISSUE TITLE
Middleware error

### ISSUE THREAD

**Issue by michaloo** [hull-ships/hull-hubspot#11]
```
» 13 Sep 2016 15:06:51.965 99 <190>1 2016-09-13T13:06:51.550366+00:00 app web.1 - - Error
» 13 Sep 2016 15:06:52.036 154 <190>1 2016-09-13T13:06:51.550382+00:00 app web.1 - - at /app/node_modules/hull/lib/middleware/client.js:85:21
» 13 Sep 2016 15:06:52.036 160 <190>1 2016-09-13T13:06:51.550384+00:00 app web.1 - - at process._tickCallback (internal/process/next_tick.js:103:7)
```

There is an error which happens inside hull-node middleware after fetching ship information.

**Comment by unity** [comment]
Do you have any more info about context? Which ship and payload ?

**Comment by michaloo** [comment]
I will investigate on that issue. It looked like there was some big latency on the `fetchShip` operation and it had a timeout.
There is #12 for an enhancement to trim middleware stack on the public WebApp, because we queue everything to the WorkerApp. It will partially solve the problem.

**Comment by unity** [comment]
Apart from an unplanned bug, fetchShip should be a memoized call and shouldn't be doing network calls each time. Other ships usually don't have this kind of issue, maybe it isn't something we should fix in the library.

Anyways, we've had a discussion about replacing this with a public redis with { key: ship_id, value: encrypted_serialized_ship_object }, Encryption key being the Ship secret that's received during calls.

**Comment by unity** [comment]
https://trello.com/c/S19PmiiC/89-middleware-error
