### ISSUE TITLE
unhandled rejection caused by redis connection error

### ISSUE THREAD

**Issue by sbellity** [hull-ships/hull-hubspot#14]
Causes the request to hang and the dyno to crash. 
We need to make sure that all public endpoints properly handle all errors. 
We also probably should have express-timeout install by default on all ships to make sure there are no loose ends and the dynos never hang.

https://github.com/expressjs/timeout

**Comment by michaloo** [comment]
Simplified timeout handling added here #16.
Do you have some error logs for that case?
