### ISSUE TITLE
Properly cast hubspot properties in Hull

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-hubspot#20]
- [ ]  Fetch custom Hubspot Properties casting and store it in Private settings
- [x] Hardcode default hubspot properties types

**Comment by michaloo** [comment]
Before every batch operation (`sendUsers`, `saveUsers` and before segment/ship related events) we do a reconciliation which download the hubspot properties list so we don't need to store it in private settings. The basic casting of arrays implemented.
