### ISSUE TITLE
We want to be able to send select user events to Hubspot

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-hubspot#23]
We want to select a list of Hull event names from a field of type event and format array and start sending events that are listed to Hubspot, same as we already do with the Segment connector

We want to have a checkbox to globally enable or disable event forwarding to Hubspot

**Comment by michaloo** [comment]
We want to use the Enterprise Custom Events feature?
http://developers.hubspot.com/docs/methods/enterprise_events/http_api
