### ISSUE TITLE
Picture isn't served anymore

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-hubspot#3]
`/picture.png` should serve the file in `/assets/picture.png`.
The folder isn't resolved by express anymore

**Comment by michaloo** [comment]
With this fix it should be served properly:
https://github.com/hull-ships/hull-hubspot/commit/3c3828b9f7d6c00168029717716feed1b62c0062#diff-9cc5d8085069032e124188ed296ebf6fR9

**Comment by unity** [comment]
👍
