### ISSUE TITLE
Install and Usage instructions need to be updated in the README

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-hubspot#4]
I can't find how to start it locally and provide it the clientID and secrets.
Is Docker mandatory to start a dev instance?

**Comment by michaloo** [comment]
I will add that today as soon as possible.
No, docker is not mandatory. You can use local nodejs installation. Following env variables have to be set before starting the app:
https://github.com/hull-ships/hull-hubspot/blob/master/.env.sample

**Comment by unity** [comment]
Ok Waiting for you to list commands to install / start-dev / build / start-production in the README.md. It seems the commands in `package.json` aren't valid anymore. Am I wrong in thinking that?

**Comment by michaloo** [comment]
Yes, you are right, this is mainly because we were to split the application into two processes - `queue` and `web` (Stephane suggested renaming `queue` to `worker`).
I've updated the scripts and README.md:
https://github.com/hull-ships/hull-hubspot/blob/master/README.md

**Comment by unity** [comment]
👍
