### ISSUE TITLE
Provide more information as to Connection status

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-hubspot#6]
We should provide more information in this screen to display the following information: 
_Depending on available information in the current state of the connector today_
- Last Sync (in the following format: `*1500 Users* on Friday, september 8 @ 12h30` or Relative Time(`17 minutes ago`))
- If a sync is ongoing, then _How many are done and Total_
- Portal ID and link to portal: `Connected to Hubspot #PORTAL_ID`

![screen shot 2016-09-08 at 11 22 03 am](https://cloud.githubusercontent.com/assets/9458/18344158/7f97a200-75b6-11e6-9202-94d20b97a02c.png)

Here's the Static markup for the screenshot above: 

``` html
<div class="panel-body">
  <div class="mb-1 ps-3">

    <h1 class="mb-0 mt-05  text-center"><i class="icon icon-hull" style="font-size:64px;"></i></h1>

    <div class="mb-1 media pb-1">
      <div class="media-left">
        <div class="media-object pr-1 pt-1">
          <div class="check valid"><i class="icon icon-valid"></i></div>
        </div>
      </div>
      <div class="media-body pt-1">
        <span class="pull-right"><a href="https://hull-hubspot.herokuapp.com/auth/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiJhMjM5YzViMi5odWxsYmV0YS5pbyIsInNoaXAiOiI1N2M5Njk0OTFlNzY4NGE3YjUwMDAwMGMiLCJzZWNyZXQiOiI1ZmExOTg2OWU4NDQxNTljZjY0MDUxN2I4OGM5MDA3ZiJ9.vYmQIYcud1SsV8wSMikX8sMJ-gWNeeOkez5g3LckA_s&amp;reset=true" class="btn btn-rounded btn-pill btn-secondary">Start over</a></span>
        <h4 class="m-0 pt-05 text-muted">Connected to Hubspot</h4>
      </div>
    </div>

    <h5>Last Sync <small class="pull-right"><strong>1500 Users</strong> on Friday, September 8 @ 12h30</small></h5>

    <hr>

    <h5>Ongoing Sync <small class="pull-right">Started 18 minutes ago</small></h5>
    <div class="progress">
      <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100" style="width: 61%;min-width: 60px;">
        <strong>9 / 5000</strong>
        <span class="sr-only">9 / 5000</span>
      </div>
    </div>

    <hr>
    <div class="">
      <div data-href="/fetchAll" class="pull-right btn btn-rounded btn-pill btn-primary">Fetch All Contacts</div>
      <strong>Connected to portal <a href="####">#1234.</a></strong>
    </div>
  </div>
</div>
```

**Comment by michaloo** [comment]
Okey, I will add most of the information right away.

The total count of contacts would need change the way we go through the Hubspot API - as far as I know - they don't expose information about total count of contacts.
What we do right now is to go through `contacts` endpoint using `offset` and `has-more` property and for each page we get we trigger hubspot->hull operation.

What we can do is what @sbellity already suggested - to first iterate over all pages and queue all other operations. We could use the simple iterator to find out the total count for contacts. But it will double the API calls.

**Comment by michaloo** [comment]
Btw. thanks for the static html 👍
