### ISSUE TITLE
Names traits

### ISSUE THREAD

**Issue by michaloo** [hull-ships/hull-hubspot#7]
In mapping object:
https://github.com/hull-ships/hull-hubspot/blob/master/server/lib/mapping-data.js#L5

We have `firstname` and `lastname` as hull traits names, but I think it should be `first_name` and `last_name`- can we safely change it?

**Comment by sbellity** [comment]
@michaloo I think that's the opposite : firstname and lastname are the hubspot field names which are mapped to hubspot/first_name and hubspot/last_name on hull

@unity do you confirm ?

**Comment by michaloo** [comment]
@sbellity - you are right, that was my misunderstanding at the time of writing that.

But having that in mind, in case when we do hull -> hubspot sync we won't save proper hull names to hubspot, Is it an expected behavior for that moment?

**Comment by michaloo** [comment]
Right now it works correctly and this is a matter of mapping strategy on which we will iterate.
